backend:
  name: github
  repo: opnprd/opnprd.github.io
  base_url: https://kltfd8s7m9.execute-api.eu-west-2.amazonaws.com
  auth_endpoint: prod/auth

publish_mode: editorial_workflow
media_folder: "assets/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        hint: Don't change this once set!
      - {label: "Featured Image", required: false, name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  # - name: "draft" # Used in routes, e.g., /admin/collections/blog
  #   label: "Draft" # Used in the UI
  #   folder: "_drafts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects" # Used in routes, e.g., /admin/collections/posts
    label: "Projects" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: Layout
        name: layout
        widget: hidden
        default: project
      - label: Title
        name: title
        widget: string
      - label: Status
        name: status
        widget: select
        options:
          - unknown
          - bid
          - won
          - started
          - completed
      - label: Start Date
        name: start_date
        widget: datetime
        default: ""
        required: false
        format: "YYYY-MM-DD"
      - label: End Date
        name: end_date
        widget: datetime
        default: ""
        required: false
        format: "YYYY-MM-DD"
      - label: Body
        name: body
        widget: markdown